version: "3.9"
services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    command: start --log trace --user root --pass root file:/data/itsg.db
    ports:
      - "8000:8000"
    volumes:
      - data:/data
      - type: bind
        source: ./database
        target: /data
  api:
    image: denoland/deno:distroless
    working_dir: /api
    command: run --allow-net src/index.ts
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./api
        target: /api
volumes:
  data:
